language: ruby
rvm:
- 2.3.1
cache: bundler
dist: trusty
sudo: required
branches:
  only:
  - dev
before_install:
- sudo add-apt-repository -y ppa:marutter/c2d4u
- sudo apt-get update
- sudo apt-get install pandoc pandoc-citeproc
- sudo apt-get install libgsl0-dev libgsl0ldbl
- gem update --system
- gem install bundler
install:
- travis_retry bundle install
script:
- bundle exec jekyll build
- bundle exec rake site:deploy
env:
  global:
