language: ruby
rvm:
- 2.3.0
cache: bundler
branches:
  only:
  - dev
before_install:
- sudo add-apt-repository -y ppa:marutter/c2d4u
- sudo apt-get update
- sudo apt-get install pandoc pandoc-citeproc
- sudo apt-get install gsl-bin libgsl0-dev
- gem update --system
- gem install bundler
install:
- travis_retry bundle install
script:
- bundle exec jekyll build
- bundle exec rake site:deploy
env:
  global:
  
